// routes.js
// Single source of truth — used by both the engine (server) and IndianBoard (client).
// Fields:
//   id           : unique route id; dual lane B = id + "b"
//   from / to    : city names
//   color        : slot color shown on board
//   length       : number of train cars required
//   ferry        : true if locomotive wild-cards are REQUIRED (water crossing)
//   locosRequired: how many locomotive cards must be in the payment (ferry routes only)
//   dualGroup    : non-null string means this city-pair has two claimable lanes;
//                  both lanes share the same dualGroup string.
//                  Lane A = id,  Lane B = id + "b"  (same color unless c2 differs — see board)

const ROUTES = [
  // ── NW ──────────────────────────────────────────────────────────────────────
  { id:"R01",  from:"Peshawar",   to:"Lahore",      color:"pink",    length:1, ferry:false, locosRequired:0, dualGroup:"Peshawar-Lahore" },
  { id:"R01b", from:"Peshawar",   to:"Lahore",      color:"green",   length:1, ferry:false, locosRequired:0, dualGroup:"Peshawar-Lahore" },
  { id:"R02",  from:"Peshawar",   to:"Jacobabad",   color:"orange",  length:3, ferry:false, locosRequired:0, dualGroup:"Peshawar-Jacobabad" },
  { id:"R02b", from:"Peshawar",   to:"Jacobabad",   color:"yellow",  length:3, ferry:false, locosRequired:0, dualGroup:"Peshawar-Jacobabad" },
  { id:"R03",  from:"Lahore",     to:"Jacobabad",   color:"red",     length:3, ferry:false, locosRequired:0, dualGroup:null },
  { id:"R04",  from:"Lahore",     to:"Bhatinda",    color:"gray",    length:2, ferry:false, locosRequired:0, dualGroup:"Lahore-Bhatinda" },
  { id:"R04b", from:"Lahore",     to:"Bhatinda",    color:"gray",    length:2, ferry:false, locosRequired:0, dualGroup:"Lahore-Bhatinda" },
  { id:"R05",  from:"Lahore",     to:"Ambala",      color:"black",   length:4, ferry:false, locosRequired:0, dualGroup:null },
  { id:"R06",  from:"Jacobabad",  to:"Karachi",     color:"white",   length:4, ferry:false, locosRequired:0, dualGroup:null },
  { id:"R07",  from:"Jacobabad",  to:"Rohri",       color:"green",   length:1, ferry:false, locosRequired:0, dualGroup:"Jacobabad-Rohri" },
  { id:"R07b", from:"Jacobabad",  to:"Rohri",       color:"blue",    length:1, ferry:false, locosRequired:0, dualGroup:"Jacobabad-Rohri" },
  { id:"R08",  from:"Bhatinda",   to:"Rohri",       color:"pink",    length:2, ferry:false, locosRequired:0, dualGroup:null },
  { id:"R09",  from:"Bhatinda",   to:"Jodhpur",     color:"green",   length:3, ferry:false, locosRequired:0, dualGroup:null },
  { id:"R10",  from:"Bhatinda",   to:"Delhi",       color:"blue",    length:3, ferry:false, locosRequired:0, dualGroup:null },
  { id:"R11",  from:"Bhatinda",   to:"Ambala",      color:"white",   length:2, ferry:false, locosRequired:0, dualGroup:"Bhatinda-Ambala" },
  { id:"R11b", from:"Bhatinda",   to:"Ambala",      color:"yellow",  length:2, ferry:false, locosRequired:0, dualGroup:"Bhatinda-Ambala" },
  { id:"R12",  from:"Rohri",      to:"Karachi",     color:"black",   length:3, ferry:false, locosRequired:0, dualGroup:null },
  { id:"R13",  from:"Ambala",     to:"Delhi",       color:"gray",    length:2, ferry:false, locosRequired:0, dualGroup:"Ambala-Delhi" },
  { id:"R13b", from:"Ambala",     to:"Delhi",       color:"gray",    length:2, ferry:false, locosRequired:0, dualGroup:"Ambala-Delhi" },
  { id:"R14",  from:"Ambala",     to:"Bareilly",    color:"orange",  length:2, ferry:false, locosRequired:0, dualGroup:null },
  { id:"R15",  from:"Karachi",    to:"Jodhpur",     color:"orange",  length:3, ferry:false, locosRequired:0, dualGroup:null },
  { id:"R16",  from:"Karachi",    to:"Bombay",      color:"gray",    length:6, ferry:true,  locosRequired:2, dualGroup:"Karachi-Bombay" },
  { id:"R16b", from:"Karachi",    to:"Bombay",      color:"gray",    length:6, ferry:true,  locosRequired:2, dualGroup:"Karachi-Bombay" },
  { id:"R17",  from:"Jodhpur",    to:"Ahmadabad",   color:"pink",    length:3, ferry:false, locosRequired:0, dualGroup:"Jodhpur-Ahmadabad" },
  { id:"R17b", from:"Jodhpur",    to:"Ahmadabad",   color:"black",   length:3, ferry:false, locosRequired:0, dualGroup:"Jodhpur-Ahmadabad" },
  { id:"R18",  from:"Jodhpur",    to:"Jaipur",      color:"red",     length:2, ferry:false, locosRequired:0, dualGroup:null },
  { id:"R19",  from:"Delhi",      to:"Jaipur",      color:"pink",    length:2, ferry:false, locosRequired:0, dualGroup:null },
  { id:"R20",  from:"Delhi",      to:"Agra",        color:"orange",  length:2, ferry:false, locosRequired:0, dualGroup:null },
  { id:"R21",  from:"Delhi",      to:"Lucknow",     color:"yellow",  length:2, ferry:false, locosRequired:0, dualGroup:null },
  { id:"R22",  from:"Delhi",      to:"Bareilly",    color:"white",   length:1, ferry:false, locosRequired:0, dualGroup:null },
  { id:"R23",  from:"Jaipur",     to:"Ratiam",      color:"yellow",  length:1, ferry:false, locosRequired:0, dualGroup:"Jaipur-Ratiam" },
  { id:"R23b", from:"Jaipur",     to:"Ratiam",      color:"orange",  length:1, ferry:false, locosRequired:0, dualGroup:"Jaipur-Ratiam" },
  { id:"R24",  from:"Jaipur",     to:"Agra",        color:"blue",    length:1, ferry:false, locosRequired:0, dualGroup:"Jaipur-Agra" },
  { id:"R24b", from:"Jaipur",     to:"Agra",        color:"white",   length:1, ferry:false, locosRequired:0, dualGroup:"Jaipur-Agra" },
  { id:"R25",  from:"Agra",       to:"Bhopal",      color:"red",     length:1, ferry:false, locosRequired:0, dualGroup:"Agra-Bhopal" },
  { id:"R25b", from:"Agra",       to:"Bhopal",      color:"pink",    length:1, ferry:false, locosRequired:0, dualGroup:"Agra-Bhopal" },
  { id:"R26",  from:"Agra",       to:"Katni",       color:"green",   length:2, ferry:false, locosRequired:0, dualGroup:null },
  { id:"R27",  from:"Agra",       to:"Lucknow",     color:"gray",    length:2, ferry:false, locosRequired:0, dualGroup:null },
  { id:"R28",  from:"Bareilly",   to:"Lucknow",     color:"gray",    length:1, ferry:false, locosRequired:0, dualGroup:null },
  { id:"R29",  from:"Bareilly",   to:"Patna",       color:"green",   length:4, ferry:false, locosRequired:0, dualGroup:null },
  { id:"R30",  from:"Lucknow",    to:"Katni",       color:"blue",    length:1, ferry:false, locosRequired:0, dualGroup:"Lucknow-Katni" },
  { id:"R30b", from:"Lucknow",    to:"Katni",       color:"black",   length:1, ferry:false, locosRequired:0, dualGroup:"Lucknow-Katni" },
  { id:"R31",  from:"Katni",      to:"Bilaspur",    color:"white",   length:1, ferry:false, locosRequired:0, dualGroup:"Katni-Bilaspur" },
  { id:"R31b", from:"Katni",      to:"Bilaspur",    color:"pink",    length:1, ferry:false, locosRequired:0, dualGroup:"Katni-Bilaspur" },
  { id:"R32",  from:"Katni",      to:"Patna",       color:"gray",    length:2, ferry:false, locosRequired:0, dualGroup:"Katni-Patna" },
  { id:"R32b", from:"Katni",      to:"Patna",       color:"gray",    length:2, ferry:false, locosRequired:0, dualGroup:"Katni-Patna" },
  { id:"R33",  from:"Patna",      to:"Calcutta",    color:"pink",    length:2, ferry:false, locosRequired:0, dualGroup:null },
  { id:"R34",  from:"Patna",      to:"Dhubri",      color:"red",     length:2, ferry:false, locosRequired:0, dualGroup:"Patna-Dhubri" },
  { id:"R34b", from:"Patna",      to:"Dhubri",      color:"blue",    length:2, ferry:false, locosRequired:0, dualGroup:"Patna-Dhubri" },
  { id:"R35",  from:"Dhubri",     to:"Calcutta",    color:"gray",    length:2, ferry:false, locosRequired:0, dualGroup:"Dhubri-Calcutta" },
  { id:"R35b", from:"Dhubri",     to:"Calcutta",    color:"gray",    length:2, ferry:false, locosRequired:0, dualGroup:"Dhubri-Calcutta" },
  { id:"R36",  from:"Dhubri",     to:"Chittagong",  color:"white",   length:2, ferry:false, locosRequired:0, dualGroup:null },
  { id:"R37",  from:"Dhubri",     to:"Jarhat",      color:"gray",    length:2, ferry:false, locosRequired:0, dualGroup:"Dhubri-Jarhat" },
  { id:"R37b", from:"Dhubri",     to:"Jarhat",      color:"gray",    length:2, ferry:false, locosRequired:0, dualGroup:"Dhubri-Jarhat" },
  { id:"R38",  from:"Jarhat",     to:"Chittagong",  color:"gray",    length:3, ferry:false, locosRequired:0, dualGroup:null },
  { id:"R39",  from:"Chittagong", to:"Calcutta",    color:"gray",    length:2, ferry:true,  locosRequired:1, dualGroup:"Chittagong-Calcutta" },
  { id:"R39b", from:"Chittagong", to:"Calcutta",    color:"gray",    length:2, ferry:true,  locosRequired:1, dualGroup:"Chittagong-Calcutta" },
  { id:"R40",  from:"Calcutta",   to:"Bilaspur",    color:"yellow",  length:4, ferry:false, locosRequired:0, dualGroup:null },
  { id:"R41",  from:"Calcutta",   to:"Raipur",      color:"blue",    length:4, ferry:false, locosRequired:0, dualGroup:null },
  { id:"R42",  from:"Calcutta",   to:"Waltain",     color:"red",     length:4, ferry:false, locosRequired:0, dualGroup:null },
  { id:"R43",  from:"Calcutta",   to:"Madras",      color:"gray",    length:8, ferry:true,  locosRequired:2, dualGroup:null },
  { id:"R44",  from:"Bilaspur",   to:"Bhopal",      color:"gray",    length:2, ferry:false, locosRequired:0, dualGroup:"Bilaspur-Bhopal" },
  { id:"R44b", from:"Bilaspur",   to:"Bhopal",      color:"gray",    length:2, ferry:false, locosRequired:0, dualGroup:"Bilaspur-Bhopal" },
  { id:"R45",  from:"Bilaspur",   to:"Raipur",      color:"red",     length:1, ferry:false, locosRequired:0, dualGroup:"Bilaspur-Raipur" },
  { id:"R45b", from:"Bilaspur",   to:"Raipur",      color:"black",   length:1, ferry:false, locosRequired:0, dualGroup:"Bilaspur-Raipur" },
  { id:"R46",  from:"Bhopal",     to:"Ratiam",      color:"black",   length:2, ferry:false, locosRequired:0, dualGroup:null },
  { id:"R47",  from:"Bhopal",     to:"Khandwa",     color:"blue",    length:2, ferry:false, locosRequired:0, dualGroup:null },
  { id:"R48",  from:"Ratiam",     to:"Ahmadabad",   color:"green",   length:1, ferry:false, locosRequired:0, dualGroup:null },
  { id:"R49",  from:"Ratiam",     to:"Khandwa",     color:"gray",    length:2, ferry:false, locosRequired:0, dualGroup:null },
  { id:"R50",  from:"Ahmadabad",  to:"Khandwa",     color:"yellow",  length:2, ferry:false, locosRequired:0, dualGroup:null },
  { id:"R51",  from:"Ahmadabad",  to:"Bombay",      color:"white",   length:3, ferry:false, locosRequired:0, dualGroup:null },
  { id:"R52",  from:"Khandwa",    to:"Manmad",      color:"red",     length:1, ferry:false, locosRequired:0, dualGroup:null },
  { id:"R53",  from:"Khandwa",    to:"Raipur",      color:"orange",  length:4, ferry:false, locosRequired:0, dualGroup:null },
  { id:"R54",  from:"Raipur",     to:"Waltain",     color:"white",   length:3, ferry:false, locosRequired:0, dualGroup:"Raipur-Waltain" },
  { id:"R54b", from:"Raipur",     to:"Waltain",     color:"green",   length:3, ferry:false, locosRequired:0, dualGroup:"Raipur-Waltain" },
  { id:"R55",  from:"Manmad",     to:"Bombay",      color:"black",   length:1, ferry:false, locosRequired:0, dualGroup:null },
  { id:"R56",  from:"Manmad",     to:"Poona",       color:"gray",    length:1, ferry:false, locosRequired:0, dualGroup:null },
  { id:"R57",  from:"Manmad",     to:"Indur",       color:"pink",    length:3, ferry:false, locosRequired:0, dualGroup:null },
  { id:"R58",  from:"Indur",      to:"Wadi",        color:"gray",    length:1, ferry:false, locosRequired:0, dualGroup:null },
  { id:"R59",  from:"Indur",      to:"Bezwada",     color:"green",   length:2, ferry:false, locosRequired:0, dualGroup:"Indur-Bezwada" },
  { id:"R59b", from:"Indur",      to:"Bezwada",     color:"yellow",  length:2, ferry:false, locosRequired:0, dualGroup:"Indur-Bezwada" },
  { id:"R60",  from:"Bombay",     to:"Calicut",     color:"gray",    length:6, ferry:true,  locosRequired:2, dualGroup:null },
  { id:"R61",  from:"Bombay",     to:"Mormugau",    color:"green",   length:1, ferry:false, locosRequired:0, dualGroup:null },
  { id:"R62",  from:"Bombay",     to:"Poona",       color:"blue",    length:1, ferry:false, locosRequired:0, dualGroup:null },
  { id:"R63",  from:"Waltain",    to:"Bezwada",     color:"black",   length:2, ferry:false, locosRequired:0, dualGroup:"Waltain-Bezwada" },
  { id:"R63b", from:"Waltain",    to:"Bezwada",     color:"orange",  length:2, ferry:false, locosRequired:0, dualGroup:"Waltain-Bezwada" },
  { id:"R64",  from:"Waltain",    to:"Madras",      color:"yellow",  length:3, ferry:false, locosRequired:0, dualGroup:null },
  { id:"R65",  from:"Poona",      to:"Mormugau",    color:"gray",    length:1, ferry:false, locosRequired:0, dualGroup:null },
  { id:"R66",  from:"Poona",      to:"Wadi",        color:"orange",  length:1, ferry:false, locosRequired:0, dualGroup:null },
  { id:"R67",  from:"Mormugau",   to:"Mangalore",   color:"black",   length:2, ferry:false, locosRequired:0, dualGroup:null },
  { id:"R68",  from:"Mormugau",   to:"Guntakal",    color:"red",     length:2, ferry:false, locosRequired:0, dualGroup:null },
  { id:"R69",  from:"Mormugau",   to:"Wadi",        color:"gray",    length:1, ferry:false, locosRequired:0, dualGroup:null },
  { id:"R70",  from:"Wadi",       to:"Guntakal",    color:"black",   length:1, ferry:false, locosRequired:0, dualGroup:"Wadi-Guntakal" },
  { id:"R70b", from:"Wadi",       to:"Guntakal",    color:"pink",    length:1, ferry:false, locosRequired:0, dualGroup:"Wadi-Guntakal" },
  { id:"R71",  from:"Bezwada",    to:"Guntakal",    color:"blue",    length:2, ferry:false, locosRequired:0, dualGroup:null },
  { id:"R72",  from:"Bezwada",    to:"Madras",      color:"red",     length:1, ferry:false, locosRequired:0, dualGroup:null },
  { id:"R73",  from:"Guntakal",   to:"Mangalore",   color:"gray",    length:2, ferry:false, locosRequired:0, dualGroup:null },
  { id:"R74",  from:"Guntakal",   to:"Madras",      color:"white",   length:2, ferry:false, locosRequired:0, dualGroup:null },
  { id:"R75",  from:"Madras",     to:"Mangalore",   color:"pink",    length:4, ferry:false, locosRequired:0, dualGroup:null },
  { id:"R76",  from:"Madras",     to:"Erode",       color:"green",   length:2, ferry:false, locosRequired:0, dualGroup:"Madras-Erode" },
  { id:"R76b", from:"Madras",     to:"Erode",       color:"orange",  length:2, ferry:false, locosRequired:0, dualGroup:"Madras-Erode" },
  { id:"R77",  from:"Mangalore",  to:"Calicut",     color:"yellow",  length:1, ferry:false, locosRequired:0, dualGroup:"Mangalore-Calicut" },
  { id:"R77b", from:"Mangalore",  to:"Calicut",     color:"white",   length:1, ferry:false, locosRequired:0, dualGroup:"Mangalore-Calicut" },
  { id:"R78",  from:"Calicut",    to:"Quilon",      color:"gray",    length:2, ferry:true,  locosRequired:1, dualGroup:"Calicut-Quilon" },
  { id:"R78b", from:"Calicut",    to:"Quilon",      color:"gray",    length:2, ferry:true,  locosRequired:1, dualGroup:"Calicut-Quilon" },
  { id:"R79",  from:"Calicut",    to:"Erode",       color:"red",     length:3, ferry:false, locosRequired:0, dualGroup:"Calicut-Erode" },
  { id:"R79b", from:"Calicut",    to:"Erode",       color:"blue",    length:3, ferry:false, locosRequired:0, dualGroup:"Calicut-Erode" },
  { id:"R80",  from:"Quilon",     to:"Erode",       color:"gray",    length:4, ferry:false, locosRequired:0, dualGroup:null },
];

module.exports = { ROUTES };